# Generated by Django 3.1.7 on 2021-03-21 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('sender', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('detail', models.TextField()),
            ],
        ),
    ]
