# Generated by Django 3.1.7 on 2021-03-21 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='num',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
