# Generated by Django 3.1.7 on 2021-03-21 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_contact_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='num',
        ),
    ]
