# Generated by Django 3.1.7 on 2021-03-26 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_short_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='detail',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='sender',
            new_name='name',
        ),
    ]
